package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Accident;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AccidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    int insert(Accident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    Accident selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    List<Accident> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    int updateByPrimaryKey(Accident record);
}