package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.CarAccident;
import org.apache.ibatis.annotations.Param;

public interface CarAccidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    int deleteByPrimaryKey(@Param("accidentId") Integer accidentId, @Param("carId") Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    int insert(CarAccident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_ACCIDENT
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    List<CarAccident> selectAll();
}