package lt.vu.mybatis.model;

public class CarAccident {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_ACCIDENT.ACCIDENT_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    private Integer accidentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_ACCIDENT.CAR_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    private Integer carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_ACCIDENT.ACCIDENT_ID
     *
     * @return the value of PUBLIC.CAR_ACCIDENT.ACCIDENT_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    public Integer getAccidentId() {
        return accidentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_ACCIDENT.ACCIDENT_ID
     *
     * @param accidentId the value for PUBLIC.CAR_ACCIDENT.ACCIDENT_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    public void setAccidentId(Integer accidentId) {
        this.accidentId = accidentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_ACCIDENT.CAR_ID
     *
     * @return the value of PUBLIC.CAR_ACCIDENT.CAR_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_ACCIDENT.CAR_ID
     *
     * @param carId the value for PUBLIC.CAR_ACCIDENT.CAR_ID
     *
     * @mbg.generated Sat Mar 27 19:17:58 EET 2021
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}